#ifndef __NormalsGenDialog__
#define __NormalsGenDialog__

/**
@file
Subclass of baseNormGenDlg, which is generated by wxFormBuilder.
*/

#include "baseNormalsOptDlg.h"

//// end generated include

#include "NormalGenLayers.h"
#include "wx/textdlg.h"

#include "PreviewWindow.h"

/** Implementing baseNormGenDlg */
class NormalsGenDialog : public baseNormGenDlg
{
	protected:
		// Handlers for baseNormGenDlg events.
		void doShowPresetContext( wxCommandEvent& event );
		void doPropertyChanged( wxPropertyGridEvent& event );
		void doAddLayer( wxCommandEvent& event );
		void doMoveUpLayer( wxCommandEvent& event );
		void doDeleteLayer( wxCommandEvent& event );
		void OnUseBackgroundLayerCheck( wxCommandEvent& event );
		void doSetOutputFileName( wxFileDirPickerEvent& event );
		void doPreviewNormalMap( wxCommandEvent& event );
		void doGenerateNormalMap( wxCommandEvent& event );
		void doLoadPreset( wxCommandEvent& event );
		void doSavePreset( wxCommandEvent& event );
	public:
		/** Constructor */
		NormalsGenDialog( wxWindow* parent, std::vector<NormalGenLayer>& inLayersRef);
	//// end generated class members

		void SetLayersRef(std::vector<NormalGenLayer>& inLayersRef);
	protected:
		int layerCount = 1;
		std::vector<NormalGenLayer>& refNormalGenLayers;

		void doPropSelected(wxPropertyGridEvent& event);

		wxString nextLayerName();
		void addBGLayer(NormalGenLayer& newLayer);
		void addLayer(NormalGenLayer& newLayer, wxPGProperty* before = nullptr);

		void PopulateLayers();





};

#endif // __NormalsGenDialog__
